### PR TITLE
.fit files can also be named .FIT

### PR DESCRIPTION
**Pull request by gotiniens**
- [] tests added / passed
I'm not really sure how to add an test for the copy_fit_files function
- [X] Ensure pre-commit formatting checks are passing
- [X]  changelog entry

My device a 920XT create files named .FIT instead of .fit, it seemed an easy fixed, so here you go :)

### CODE REVIEW

**Comment by fgebhart** [comment]
Hi @gotiniens :wave:

Awesome! Thanks for your contribution! Good catch, upper case `.FIT` could of course be a quite common thing.

However, I want to point out one more thing. You touched the `fit_collector.py` which is in charge of copying the fit files from your device to the target directory on the machine workoutizer is running on (mostly referenced with `path_to_trace_dir`). Since we also want these "collected" files to be imported subsequently, we would have to also touch the `file_importer.py`.

Using the `.lower()` approach works just fine. Could you please also apply this to the following lines?

* https://github.com/fgebhart/workoutizer/blob/main/wkz/file_importer.py#L239 to also support the import of upper case `.GPX` files
* https://github.com/fgebhart/workoutizer/blob/main/wkz/file_importer.py#L242 to also support the import of upper case `.FIT` files
* https://github.com/fgebhart/workoutizer/blob/main/wkz/file_importer.py#L261 required to initially get a list of all files having the supported formats

That should cover everything. No worries about the tests, I will add them afterwards.

Thanks again, cheers.

**Comment by gotiniens** [comment]
No problem, thank you for the awesome piece of software!

Although I am not completly sure how the docker dev environment works, It imported my example FIT file, so it looks to be working now.

```06-14 17:38:02 - DEBUG - wkz.file_importer - triggered file importer on path: /workspaces/workoutizer/tracks
06-14 17:38:02 - DEBUG - wkz.tools.sse - File Import started: Found 1 activity files in /workspaces/workoutizer/tracks. Please wait.
06-14 17:38:02 - INFO - wkz.file_importer - importing /workspaces/workoutizer/tracks/B1GC4959.FIT ...
06-14 17:38:02 - DEBUG - wkz.file_importer - parsing FIT file ...
06-14 17:38:03 - DEBUG - wkz.file_helper.fit_parser - found date: 2021-01-16 12:14:48+00:53
```
I'm not sure about the merge conflict, but it seems te be easily resolved when merging.

**Comment by fgebhart** [comment]
Awesome, thanks! 🎉 

The merge conflict was caused by another PR which I merged in between - resolved it.

**Comment by fgebhart** [comment]
@gotiniens 

Also, if you have trouble spinning up the docker environment, feel free to open a issue in case things are not behaving like expected on your side.

The docker environment is useful when doing development and running tests and so on. For actually running a "productive" version of workoutizer I would rather suggest to set up an additional (isolated) virtual environment and simply install workoutizer using `pip install workoutizer`. If you should have questions/issues on that I'd happy to discuss this also in either an issue or in the [discussions](https://github.com/fgebhart/workoutizer/discussions).

Enjoy!

**Pull request merged**
